### PR TITLE
fix: Compatibility with semantic-release v20

### PR DESCRIPTION
**Pull request by saitho**
Import semantic-release functions via ESM.

Fixes: #38

### CODE REVIEW

**Comment by saitho** [comment]
Todo: Automated tests for different semantic-release versions

**Comment by EinfachHans** [comment]
Awesome, looking forward for this 😊

**Comment by saitho** [comment]
This change finally seems to work. It introduces breaking changes:

* Dropped compatibility to semantic-release before v20: ESM modules can not be used with v19.
* Remove `branchNames`: I used this opportunity to remove the already deprecated setting `branchNames`
* Rename `branches` into `backmergeBranches`: in order to avoid collision with the semantic-release `branches` setting, the setting we use was renamed to `backmergeBranches`. Before merging this I will publish another bugfix release for the old version introducing a proper deprecation.

**Pull request merged**
